version: "3"

services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: notific_proj
    volumes: 
      - ./calender:/calender
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"]
    env_file: db_keys.txt

  db:
    image: postgres:latest
    container_name: my_db
    ports: 
      - '5432:5432'
    env_file: db_keys.txt

  redis:
    image: redis:latest
    container_name: redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_wb
    volumes:
      - ./calender:/calender
    depends_on:
      - db
      - redis
      - web
    env_file:
      - db_keys.txt
    ports:
      - "5555:5555"
    command: bash -c "celery -A calender worker -l info -B"