# Generated by Django 3.2.6 on 2021-08-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_event_notification_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='notification_time',
        ),
    ]
