# Generated by Django 3.2.6 on 2021-08-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_event_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notificate',
            field=models.IntegerField(choices=[[1, 'За неделю'], [2, 'За день'], [3, 'За 4 часа'], [4, 'За 2 часа'], [5, 'За час']], default=1),
        ),
    ]
