# Generated by Django 3.2.6 on 2021-08-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_alter_event_notificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='notificaton_time',
            new_name='notification_time',
        ),
    ]
