# Generated by Django 3.2.6 on 2021-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_rename_notificaton_time_event_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
