# Generated by Django 3.2.6 on 2021-08-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_alter_event_data_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data_to',
            new_name='date_to',
        ),
    ]
