# Generated by Django 3.2.6 on 2021-08-20 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_rename_data_to_event_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notificate',
            field=models.DurationField(blank=True, choices=[[datetime.timedelta(days=7), 'За неделю'], [datetime.timedelta(days=1), 'За день'], [datetime.timedelta(seconds=14400), 'За 4 часа'], [datetime.timedelta(seconds=7200), 'За 2 часа'], [datetime.timedelta(seconds=3600), 'За час']], default=3, null=True),
        ),
    ]
